[package]
name = "oss-rtld"
version = "0.1.0"
edition = "2021"

[dependencies]
static_assertions = "1.1.0"
modular-bitfield = "0.11.2"

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 's'
panic = 'abort'